### ISSUE TITLE
How to route a html or a static folder for android with ktor

### ISSUE THREAD

**Issue by happylinhdn** [nphausg/android.embeddedserver#1]
I see your implement just return a hello world text when apply to localhost. Could we config route to response a HTML static file? i don't know where is the root folder for our server to put file.

**Comment by happylinhdn** [comment]
for more detail: I can run a static HTML file, but can not run with react-js sources. can you point me the component/engine to support react-js source

**Comment by nphau** [comment]
Thanks for your comment, I think when you work with files, it is exactly the same with the android Systems. You can use Assets, Raw, or even files on your phone. It depends on how you provide for ktor. Easy way I think, you can read File and use respondFile

https://ktor.io/docs/responses.html
```
fun Application.main() {
    routing {
        get("/download") {
            val file = File("files/ktor_logo.png")
            call.response.header(
                HttpHeaders.ContentDisposition,
                ContentDisposition.Attachment.withParameter(ContentDisposition.Parameters.FileName, "ktor_logo.png")
                    .toString()
            )
            call.respondFile(file)
        }
    }
}
```

**Comment by WatsonYao** [comment]
after try and try, i found a work way on android project.
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/10070520/229683928-801cf2a9-9427-4746-b5f2-54af2470149a.png">

**Comment by nphausg** [comment]
thank for your recommendation updated in source code
