### ISSUE TITLE
Setup returning Json response with a specific endpoint

### ISSUE THREAD

**Issue by hieuwu** [nphausg/android.embeddedserver#3]
## :bulb: Is your feature request related to a problem? Please describe.
Currently, the demo return data dirrectly with the code. It would be nice if we can configure some endpoints mapped with some json files, such that whenever we want to test a new response, we only need to update json file and the endpoint

## :white_check_mark: Describe the solution you'd like
Setup a basic endpoint to demonstrate the response with json

## :part_alternation_mark: Describe alternatives you've considered**
None

## :construction: Additional context
None

**Comment by WatsonYao** [comment]
Thanks so much for this demo. I was wondering if it would be possible to add a post method to the demo?

**Comment by hieuwu** [comment]
> Thanks so much for this demo. I was wondering if it would be possible to add a post method to the demo?

Yes we can add all the http methods. Will add these in the near future 🤣

**Comment by WatsonYao** [comment]
> 

Thank you very much. I tried the post method on the ktor official website and it works now. I'm not very familiar with using static HTML. The official static("assets") doesn't seem to work on Android.

**Comment by WatsonYao** [comment]
I also encountered another difficulty, which is that when integrating ktor and then proguard-rules.pro(minifyEnabled true) and packaging, there will be errors indicating that some initialization is missing. If not minifyEnabled, it can be used normally.  
  
#-keep class io.ktor.** { *; }
#-keep class kotlinx.coroutines.** { *; }
#-keepclassmembers class io.ktor.** { volatile <fields>; }
#-keepclassmembers class kotlinx.** { volatile <fields>; }
#-dontwarn kotlinx.atomicfu.**
#-dontwarn io.netty.**
#-dontwarn com.typesafe.**
#-dontwarn org.slf4j.**

**Comment by nphausg** [comment]
Hi @WatsonYao , I've updated in source code , you can check it out
Ref: https://ktor.io/docs/server-static-content.html

<img width="246" alt="Screenshot 2024-04-10 at 23 16 55" src="https://github.com/nphausg/android.embeddedserver/assets/13111806/407bfb49-b566-4ed4-9f5b-eb3e8da93941">


```kotlin
staticResources("/static", ""){
   default("index.html")
}
```
