### ISSUE TITLE
Setup return web page and display it

### ISSUE THREAD

**Issue by hieuwu** [nphausg/android.embeddedserver#4]
## :bulb: Is your feature request related to a problem? Please describe.
For some cases, we might need to get response as html based such that it is more flexible to handle in app

## :white_check_mark: Describe the solution you'd like
Create an endpoint attached with a webpage, when user hit that endpoint, return webpage and display the content

## :part_alternation_mark: Describe alternatives you've considered**
None

## :construction: Additional context
None

**Comment by nphausg** [comment]
Thank for your recommendation updated in source code 
Ref: https://ktor.io/docs/server-static-content.html

<img width="246" alt="Screenshot 2024-04-10 at 23 16 55" src="https://github.com/nphausg/android.embeddedserver/assets/13111806/407bfb49-b566-4ed4-9f5b-eb3e8da93941">


```kotlin
staticResources("/static", ""){
   default("index.html")
}
```
